services:
  - type: web
    name: fortis-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_TO
        sync: false
      - key: RENDER_EXTERNAL_URL
        value: https://fortis-steel-bot.onrender.com
